### ISSUE TITLE
Design the moderator dashboard

### ISSUE THREAD

**Issue by jpic** [political-memory/political_memory#68] opened 2016-05-26 23:10 UTC
Currently, [administrators use the admin to add recommendations](http://memopol.readthedocs.io/en/pr/usage.html#managing-vote-recommendations).

This process is suboptimal, your mission, if you accept it, is to propose an alternative user experience design, oriented for journalists.

If someone would be able to work full time on it, the team has agreed to help making a crowdfunding campaign.

**Comment by djangocreation** [comment] 2016-05-27 05:35
Hi, 

Are you already have ideas for design ? Bootstrap ? Jquery UI ? 

If I well understood, this goal is manage connections, registration for that journalists could be add recommendations, isn't it ?

**Comment by njoyard** [comment] 2016-05-27 06:41
I think the first step is to define the user experience. We should start by writing test cases. Then we can work on the UX/UI and only then choose the right tools for the job.

**Comment by njoyard** [comment] 2016-05-27 06:50
See #70. I think a dossier page could be a good entry point for adding recommendations.

**Comment by jpic** [comment] 2016-05-27 17:58
Absolutely, this issue is about user experience: how can we optimize the UI so that the moderator can accomplish all moderation tasks with the least number of windows and user action.

For details about the user stories and how they are currently usable, please refer to the [user documentation](http://memopol.readthedocs.io/en/master/usage.html).

**Comment by njoyard** [comment] 2016-08-09 07:06
Duplicate of #113

**Closed by njoyard** 2016-08-09 07:06 UTC
